#!usr/bin/env php
<?php
/**
 * alza - a simple framework for PHP Developers
 *
 * @author   izni burak demirtaş (@bimacoding) <bimacoding@gmail.com>
 * @url      <https://github.com/bimacoding/alza>
 * @license  The MIT License (MIT) - <http://opensource.org/licenses/MIT>
 */

require __DIR__.'/vendor/autoload.php';

use Alza\Kernel\Application;
use App\Console\Application as ConsoleApplication;
use Symfony\Component\Console\Application as SymfonyApplication;

$app = new Application;

define('Alza_VERSION', $app->version());
define('APP_ENV', strtolower(config('app.env')));

$console = new ConsoleApplication(new SymfonyApplication("        _             
__ _ | | ____  __ _ 
/ _` || ||_  / / _` |
| (_| || | / / | (_| |
\__,_||_|/___| \__,_| v" . Alza_VERSION . "
  alza - Simple PHP Framework"), $app);
$console->run();
